name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'npm'

      # Debugging: Print Node.js and npm versions
      - name: Print Node.js and npm versions
        run: |
          echo "Node.js version: $(node -v)"
          echo "npm version: $(npm -v)"

      - name: Install dependencies
        run: npm install

      # Debugging: Print the list of installed dependencies
      - name: List installed dependencies
        run: npm list

      - name: Build project
        run: npm run build

      # Debugging: Print the contents of the build directory
      - name: List output files
        run: |
          echo "Contents of the dist directory:"
          ls -alh dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deployment

      # Debugging: Verify Deployment
      - name: Verify Deployment
        run: |
          echo "Deployment to gh-pages was triggered. Check the action's output above for success or failure."
